# Generated by Django 5.0.4 on 2024-05-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='id',
        ),
        migrations.AddField(
            model_name='list',
            name='list_id',
            field=models.BigAutoField(default='exit', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='list_name',
            field=models.CharField(max_length=50),
        ),
    ]
