# Generated by Django 5.0.4 on 2024-05-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_remove_list_id_list_list_id_alter_list_list_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='list_id',
        ),
        migrations.AddField(
            model_name='list',
            name='id',
            field=models.BigAutoField(auto_created=True, default='exit', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='list_name',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
